### ISSUE TITLE
open issue and pull request fail?

### ISSUE THREAD

**Issue by darkz1984** [yuki-kimoto/gitprep#105]
gitprep version 2.3,open issue and pull request fail whith http return code 500...

**Comment by darkz1984** [comment]
I found

> 
[Tue Aug  9 13:54:22 2016] [error] DBD::SQLite::db prepare failed: near ",": syntax error. Following SQL is executed.
 select , "open_user"."id" as "open_user.id" from "issue" left join project on issue.project = project.row_id left join user as open_user on issue.open_user = open_user.row_id where ( issue.open = ?  and pull_request = ?  and project.id = ?  ) 
(DBIx::Custom::_create_query) at template /issues.html.ep line 17
39:     eval { require Carp::Heavy };
40:     return $@ if $@;
41:     goto &shortmess_real;
42: }
43: 
44: sub croak   { die  shortmess @_ }
45: sub confess { die  longmess  @_ }
46: sub carp    { warn shortmess @_ }
47: sub cluck   { warn longmess  @_ }
48: 
49: 1;

in  log/production.log
Is the database structre have some problem?

**Comment by yuki-kimoto** [comment]
Can you restart GitPrep?

**Comment by darkz1984** [comment]
restarted it for some times.

**Comment by ThomasMcVay** [comment]
I'm able to open a pull request, and view it on the requestor's account page as long as I have created a separate branch, but when I try to view the pull request from the origin account I get the following error:

[Wed Aug 10 22:43:30 2016] [error] pull_request invalid user id at /opt/gitprep/extlib/lib/perl5/Mojo/Template.pm line 181.
176:     CORE::die Mojo::Exception->new(shift)
177:       ->trace->inspect($self->unparsed, $self->code)->verbose(1);
178:   };
179: 
180:   my $output;
181:   return eval { $output = $compiled->(@_); 1 } ? $output : $@;
182: }
183: 
184: sub render { shift->parse(shift)->process(@_) }
185: 
186: sub render_file {

Also it is strange that there is "Merge Pull Request" on the requestor's version of the page. Is this expected behavior?

**Comment by yuki-kimoto** [comment]
@darkz1984 

Please tell me what you did. 

Can you display issue list page, for example  "/kimoto/pull1/issues".

Next, you click "New issue" button.

Next, you input form and submit new issue.

When you have error message?

**Comment by yuki-kimoto** [comment]
@ThomasMcVay 

Try the following and see output.

open templates/pull.html.ep and write the following code.

    warn dumper {
      base_user_id => $base_user_id,
      base_project_id => $base_project_id,
      isseu_number => $issue_number,
      issue => $issue,
      pull_reqeust => $pull_request,
      base_project_row_id => $base_project_row_id,
      base_project => $base_project,
    };

just before the following lines.

    Carp::croak "pull_request invalid user id"
      if $base_user_id ne $base_project->{'user.id'};
    Carp::croak "pull_request invalid project id"
      if $base_project_id ne $base_project->{id};

and run server for development

    ./morbo

and access URL "http://xxx.xxx.xxx.xxx:3000", and go error page.

You can get output on STDOUT.

Please tell me the output.

**Comment by ThomasMcVay** [comment]
I think I see the issue now. base-fork-btn and head-fork-btn on compare.html.ep don't show up for me at all unless I force it via the url. I initially assumed you hadn't implemented that part, but it seems that there is a problem either getting $base_user_id or $target_user_id for me. Looking more into it.

I'm going to try your suggestion now.

**Comment by ThomasMcVay** [comment]
So I submitted a pull request that fixes the behavior I was seeing where the fork buttons weren't showing up. Forgive me if I've botched the style anywhere, I don't do much work in perl. Your warn dumper trick was very useful.

The buttons all work and it redirects you to the correct url now, however in morbo now, when it redirects you to a link such as http://192.168.0.146:3000/ThomasMcVay/SourceControlTesting/compare/master...TestUser:mychanges

I'm seeing a db GET error that says Page not found.

`	
{
  "cb" => sub { "DUMMY" },
  "config" => {
    "admin" => {},
    "basic" => {},
    "data_dir" => "/opt/gitprep/data",
    "hypnotoad" => {
      "listen" => [
        "http://*:10020"
      ]
    },
    "reverse_proxy" => {}
  },
  "project" => "SourceControlTesting",
  "rev1" => "master",
  "rev2" => "TestUser:mychanges",
  "user" => "ThomasMcVay"
}`

`
[Fri Aug 12 00:28:42 2016] [debug] 200 OK (1.778382s, 0.562/s)
[Fri Aug 12 00:28:45 2016] [debug] GET "/ThomasMcVay/SourceControlTesting/compare/master...TestUser:mychanges"
[Fri Aug 12 00:28:45 2016] [debug] Routing to a callback
[Fri Aug 12 00:28:45 2016] [debug] Routing to a callback
[Fri Aug 12 00:28:45 2016] [debug] Routing to a callback
[Fri Aug 12 00:28:45 2016] [debug] Rendering cached template "/compare.html.ep"
[Fri Aug 12 00:28:47 2016] [debug] Template "not_found.development.html.ep" not found
[Fri Aug 12 00:28:47 2016] [debug] Template "not_found.html.ep" not found
[Fri Aug 12 00:28:47 2016] [debug] Rendering cached template "mojo/debug.html.ep"
[Fri Aug 12 00:28:47 2016] [debug] Rendering cached template "mojo/menubar.html.ep"`

**Comment by ThomasMcVay** [comment]
Additionally, urls that match the default branch such as this:

http://192.168.0.146:10020/ThomasMcVay/SourceControlTesting/compare/master...TestUser:master

will show a page without error. However even if a commit has been made to TestUser:master it will show that "There isn't anything to compare" which makes me suspect that it's actually comparing ThomasMcVay:master to ThomasMcVay:master instead of comparing ThomasMcVay:master to TestUser:master.
